"""empty message

Revision ID: 4ea4fbcc75a2
Revises: 9de2c7ba289e
Create Date: 2021-09-19 03:39:25.757693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea4fbcc75a2'
down_revision = '9de2c7ba289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protector', sa.Column('public_mode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protector', 'public_mode')
    # ### end Alembic commands ###
