"""empty message

Revision ID: 50cc8c5368f1
Revises: ab40e93db4a9
Create Date: 2021-09-18 05:13:12.972889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cc8c5368f1'
down_revision = 'ab40e93db4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['server_filename'])
    op.add_column('role', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'priority')
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
