"""empty message

Revision ID: 8b9e87fabece
Revises: 02a561625388
Create Date: 2021-06-02 04:30:50.408083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9e87fabece'
down_revision = '02a561625388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('creation')

    # ### end Alembic commands ###
