"""empty message

Revision ID: 9de2c7ba289e
Revises: 9182a783b314
Create Date: 2021-09-19 01:25:50.758310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de2c7ba289e'
down_revision = '9182a783b314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('protector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'protector', ['protector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'protector_id')
    # ### end Alembic commands ###
