"""empty message

Revision ID: ab40e93db4a9
Revises: ce6482f21155
Create Date: 2021-07-29 01:42:38.081461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab40e93db4a9'
down_revision = 'ce6482f21155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('downloadable', sa.Boolean(), nullable=True))

    op.alter_column('file', 'server_filename',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False,
                    unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'downloadable')

    op.alter_column('file', 'server_filename',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True,
                    unique=False)
    # ### end Alembic commands ###
