"""empty message

Revision ID: ce6482f21155
Revises: 1c49521de9a2
Create Date: 2021-07-27 03:50:47.038929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6482f21155'
down_revision = '1c49521de9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('started', sa.DateTime(), nullable=True))
    op.add_column('release', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'date')
    op.drop_column('project', 'started')
    # ### end Alembic commands ###
